# Generated by Django 4.1.5 on 2023-02-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="plotPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("description", models.TextField()),
                ("mobile_no", models.CharField(max_length=10)),
                (
                    "plot_type",
                    models.CharField(
                        choices=[
                            ("resale", "Resale"),
                            ("primarymarketproperty", "Primary-Market Property"),
                        ],
                        default="Resale",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
