# Generated by Django 4.1.5 on 2023-02-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotpost",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="propapp\\images"),
        ),
        migrations.AddField(
            model_name="plotpost",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="propapp\\images"),
        ),
        migrations.AddField(
            model_name="plotpost",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="propapp\\images"),
        ),
        migrations.AddField(
            model_name="plotpost",
            name="image4",
            field=models.ImageField(blank=True, null=True, upload_to="propapp\\images"),
        ),
        migrations.AddField(
            model_name="plotpost",
            name="image5",
            field=models.ImageField(blank=True, null=True, upload_to="propapp\\images"),
        ),
        migrations.AddField(
            model_name="plotpost",
            name="image6",
            field=models.ImageField(blank=True, null=True, upload_to="propapp\\images"),
        ),
        migrations.AddField(
            model_name="plotpost",
            name="mainimage",
            field=models.ImageField(blank=True, null=True, upload_to="propapp\\images"),
        ),
    ]
