# Generated by Django 4.1.5 on 2023-02-19 03:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("propapp", "0004_alter_plotpost_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotpost",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="heading",
                unique=True,
            ),
        ),
    ]
