# Generated by Django 4.1.5 on 2023-02-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propapp", "0005_alter_plotpost_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotpost",
            name="plot_type",
            field=models.CharField(
                choices=[
                    ("Resale", "Resale"),
                    ("Primary-Market Property", "Primary-Market Property"),
                ],
                default="Resale",
                max_length=100,
            ),
        ),
    ]
