# Generated by Django 4.1.5 on 2023-02-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propapp", "0006_alter_plotpost_plot_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotpost",
            name="plot_type",
            field=models.CharField(
                choices=[
                    ("Resale", "resale"),
                    ("Primary-Market Property", "primarymarketroperty"),
                ],
                default="Resale",
                max_length=100,
            ),
        ),
    ]
