# Generated by Django 4.1.5 on 2023-02-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propapp', '0007_alter_plotpost_plot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotpost',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='plotpost',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='plotpost',
            name='image6',
        ),
        migrations.AddField(
            model_name='plotpost',
            name='admap',
            field=models.TextField(default='hello'),
        ),
    ]
