# Generated by Django 4.1.5 on 2023-02-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propapp", "0008_remove_plotpost_image4_remove_plotpost_image5_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotpost",
            name="admap",
            field=models.TextField(),
        ),
    ]
