# Generated by Django 4.1.5 on 2023-02-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propapp", "0010_plotpost_image4_plotpost_image5"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotpost",
            name="plot_size",
            field=models.CharField(default="ee", max_length=225),
        ),
    ]
