# Generated by Django 4.1.5 on 2023-02-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propapp", "0012_alter_plotpost_plot_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotpost",
            name="city",
            field=models.CharField(default="indore", max_length=50),
        ),
    ]
