# Generated by Django 4.1.5 on 2023-02-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propapp", "0013_plotpost_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotpost",
            name="city",
            field=models.CharField(max_length=50),
        ),
    ]
