# Generated by Django 4.1.5 on 2023-02-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propapp", "0014_alter_plotpost_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_contact", models.CharField(max_length=50)),
                ("mobile_contact", models.CharField(max_length=50)),
                ("email_contact", models.CharField(max_length=50)),
                ("city_contact", models.CharField(max_length=50)),
                ("location_contact", models.CharField(max_length=50)),
                ("message_contact", models.TextField()),
            ],
        ),
    ]
