# Generated by Django 4.1.5 on 2023-02-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("propapp", "0015_contact"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="contact",
            new_name="contactInfo",
        ),
    ]
