# Generated by Django 4.1.5 on 2023-03-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propapp", "0019_remove_plotpost_image5_plotpost_ytvideo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotpost",
            name="ytvideo",
            field=models.TextField(),
        ),
    ]
