# Generated by Django 4.1.5 on 2023-03-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("propapp", "0020_alter_plotpost_ytvideo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plotpost",
            name="image4",
        ),
    ]
